# SPDX-FileCopyrightText: 2021 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

# the following config is for teaching kustomize where to look at when substituting vars.
# It requires kustomize v2.1.0 or newer to work properly.

varReference:
- path: metadata/annotations
- path: webhooks/clientConfig/url
  kind: MutatingWebhookConfiguration
- path: webhooks/clientConfig/url
  kind: ValidatingWebhookConfiguration
