# SPDX-FileCopyrightText: 2021 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

# use hack/gen-certs.sh script to generate the certificates or provide your own certificates

secretGenerator:
  - name: webhook-server-cert
    namespace: system
    files:
      - tls.crt=tls/terminal-controller-manager-tls.pem
      - tls.key=tls/terminal-controller-manager-tls-key.pem
    type: "kubernetes.io/tls"
