apiVersion: dashboard.gardener.cloud/v1alpha1
kind: Terminal
metadata:
  annotations:
    dashboard.gardener.cloud/operation: keepalive
  namespace: garden-coretmp
  name: term-lukas-hib
spec:
  host:
    credentials:
      serviceAccountRef:
        name: seed-myseed
        namespace: gardentmp
    namespace: shoot--core--mycluster
    pod:
      container:
        image: eu.gcr.io/gardener-project/gardener/ops-toolbelt:0.9.0
  target:
    credentials:
      serviceAccountRef:
        name: lukas-hib.kubeconfig
        namespace: garden-coretmp
    kubeconfigContextNamespace: default
    temporaryNamespace: true
    bindingKind: ClusterRoleBinding
    roleName: cluster-admin
#    apiServer:
##      serviceRef:
##        name: kubernetes
##        namespace: default
#      server: https://kubernetes.default.svc
