# SPDX-FileCopyrightText: 2021 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

resources:
- ../../../../secret
- ../../../../default # provided by kubebuilder, we try to leave most of the generated resources by kubebuilder untouched if possible
- ../../../../webhook # we only need the service
- kubeconfig-secret.yaml

patchesStrategicMerge:
- manager_kubeconfig_patch.yaml
- manager_auth_proxy_kubeconfig_patch.yaml

configMapGenerator:
  - files:
      - config.yaml
    name: controller-manager-configmap
